"""Initial migration.

Revision ID: 0a024728bf0c
Revises: 7364af2e8412
Create Date: 2024-08-12 01:54:06.129669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a024728bf0c'
down_revision = '7364af2e8412'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('admin_manager_replies')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_manager_replies', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
