"""Initial migration.

Revision ID: 7364af2e8412
Revises: 26fd8aac9bb5
Create Date: 2024-08-12 01:35:04.868013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7364af2e8412'
down_revision = '26fd8aac9bb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_manager_replies', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('admin_manager_replies')

    # ### end Alembic commands ###
